kumuluzee:
  name: lokacijskiopomniki
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/LokacijskiOpomnikiDS
      connection-url: jdbc:postgresql://localhost:5432/lokacijskiopomniki
      username: postgres
      password: postgres
      max-pool-size: 20