kumuluzee:
  name: lokacijskiopomniki
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/LokacijskiOpomnikiDS
      connection-url: jdbc:postgresql://localhost:5432/uporabniki
      username: postgres
      password: postgres
      max-pool-size: 20
  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 30
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/LokacijskiOpomnikiDS
      disk-space-health-check:
        threshold: 100000000
